use crate::index::NameIndex;
use crate::listable::Listable;
use crate::relic::Relic;
use std::fs;
use std::path::Path;

pub mod ability;
pub mod arcane;
pub mod avionic;
pub mod custom;
pub mod drone;
pub mod flavour;
pub mod focus_upgrade;
pub mod fusion_bundle;
pub mod gear;
pub mod intrinsic;
pub mod key;
pub mod manifest;
pub mod mod_set;
pub mod nightwave;
pub mod other;
pub mod railjack;
pub mod railjack_weapon;
pub mod recipe;
pub mod region;
pub mod relic;
pub mod resource;
pub mod sentinel;
pub mod sortie_reward;
pub mod upgrade;
pub mod warframe;
pub mod weapon;
